# Generated by Django 5.1.2 on 2024-11-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='images/default_item_logo.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
